services:
  k8s:
    build:
      context: .
      network: host
    image: k8s-one:latest
    container_name: k8s-one
    hostname: k8s-one
    privileged: true
    cgroup: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys:/sys:rw
      - /lib/modules:/lib/modules:ro
      - ./data/etcd:/var/lib/etcd
      - ./data/containerd:/var/lib/containerd
      - ./data/kubelet:/var/lib/kubelet
      - ./data/pki:/etc/kubernetes/pki
      - ./data/kubernetes:/etc/kubernetes
      - ./data/rook:/var/lib/rook
    ports:
      - "6443:6443"
      - "8082:30080"
      - "8443:30443"
    restart: unless-stopped
