apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-ceph-cluster.yaml
  - 02-ceph-block-pool.yaml
  - 03-block-storage-class.yaml
  - 04-ceph-filesystem.yaml
  - 05-filesystem-storage-class.yaml
  - 06-dashboard-namespace.yaml
  - 07-dashboard-service.yaml
  - 08-dashboard-ingress.yaml

secretGenerator:
  - name: ceph-basic-auth
    namespace: ceph-dashboard
    envs: ["secrets/ceph.env"]
    options:
      disableNameSuffixHash: true
