apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-crds.yaml
  - 01-namespace.yaml
  - 02-ipaddresspool.yaml
  - 03-l2advertisement.yaml
  - 04-rbac.yaml
  - 05-controller.yaml
  - 06-speaker.yaml
  - 07-webhook.yaml
