apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-service-account.yaml
  - 03-cluster-role.yaml
  - 04-cluster-role-binding.yaml
  - 05-deployment.yaml
  - 06-service.yaml
  - 07-ingress.yaml
  - 08-certificate.yaml
