apiVersion: v1
kind: Secret
metadata:
  name: yugabyte
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: yugabyte
  url: https://charts.yugabyte.com
  project: default
