apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work-fs
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 2Gi
