apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-conf-persistent-volume-claim.yaml
  - 03-work-persistent-volume-claim.yaml
  - 04-deployment.yaml
  - 05-service.yaml
  - 06-dns-tcp-service.yaml
  - 07-dns-udp-service.yaml
  - 08-ingress.yaml
  - 09-certificate.yaml
