apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-crds.yaml
  - 01-namespace.yaml
  - 02-rbac.yaml
  - 03-deployments.yaml
  - 04-services.yaml
  - 05-webhooks.yaml
  - cluster-issuer.yaml
